name: Continuous integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# GitHub Actions usage is FREE for both public repositories and self-hosted runners.
# We can use it to build our project and do some automated builds and in future quality tests.
# https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

jobs:

  pull_request:
    name: build (pull request)
    if: ${{ github.ref != 'refs/heads/master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # checkout project
      - uses: actions/checkout@v3

      # setup go
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      # dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -y install dos2unix

      # build PR
      - name: Build translations
        working-directory: utils
        run: |
          go run .

      # view differences on PR
      - name: View changes
        run: |
          find . -type f -name '*.vdf' -exec unix2dos --quiet {} \;
          git diff origin/master

  release:
    name: build (master)
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # checkout project
      - uses: actions/checkout@v3

      # setup go
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      # build master
      - name: Build translations
        working-directory: utils
        run: |
          go run .

      # commit progress.md on master
      # if we want this, need to enable write permissions for the github actions bot, see:
      # https://user-images.githubusercontent.com/2881159/127678772-776865c9-ca74-449b-a6df-8e95a0471560.png
      # build master
      #- name: Build translations (only on master)
      #  working-directory: utils
      #  run: |
      #    go run . | grep -v 'go: ' > ../PROGRESS.md
      #
      # - name: Update translation progress (only on master)
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     message: '[CI] update translation progress'
      #     default_author: github_actions
      #     add: 'PROGRESS.md'

