name: Continuous integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# GitHub Actions usage is FREE for both public repositories and self-hosted runners.
# We can use it to build our project and do some automated builds and in future quality tests.
# https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

jobs:
  release:
    name: build translations
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      #checkout project
      - uses: actions/checkout@v3

      # setup go
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17'

      # translations
      - name: Build translations
        working-directory: utils
        run: go run . > /report/output.txt

      # fetch changed files
      - name: Show changed files
        run: git status

      # fetch the differences
      - name: Show diff
        run: git diff
